# Change these first
owner: YAT-Publish # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: YATeam Web
    url: https://www.yateam.cc
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: Hashi(橋)
    url: https://hashi.icu
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: Hashi Proxy for CNM
    url: https://fast.hashi.icu
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: Haty
    url: https://hashi.sbs
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: Haty Proxy for CNM
    url: https://chat.hashi.icu
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: Haty Meet
    url: https://meet.hashi.sbs
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: YATeam API
    url: https://api.yateam.cc
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: YAT OSS
    url: https://files.yatserver.com/hashi/hashi/3d8fda85-1e67-45ed-8b31-3b0f02dd5c26.jpg
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: CodeProxy
    url: https://codeproxy.net
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: GitHub Proxy
    url: https://git.codeproxy.net
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: Picapica Download Page (Not a server or proxy)
    url: https://picacg.yacg.asia
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: QQBot Q
    url: $QQBOY_Q
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
  - name: QQBot Z
    url: $QQBOT_Z
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 YAT-Check"
    expectedStatusCodes:
      - 0
      - 200
      - 201
      - 301
      - 302
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  js: "const links=document.querySelectorAll('a');const hostRegex=/^https?:\/\/raw\.githubusercontent\.com/;links.forEach(link=>{if(hostRegex.test(link.href)){link.href='https://ghproxy.com'+link.href}});"
  cname: status.yatserver.com
  # baseUrl: /your-repo-name
  logoUrl: https://img.yateam.cc/images/2022/06/13/hashid59ff7816f045287.png
  name: YATeam Web Services Status Page
  introTitle: "**YATeam Org.** For the dawn of tomorrow."
  introMessage: Online status of many services including Hashi(橋), Haty, APIs used, etc.
  navbar:
    - title: Status
      href: /
    - title: Hashi
      href: https://hashi.icu
    - title: Haty
      href: https://hashi.sbs

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
